<?xml version="1.0" encoding="UTF-8"?>
<ecore:EPackage xmi:version="2.0"
    xmlns:xmi="http://www.omg.org/XMI" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
    xmlns:ecore="http://www.eclipse.org/emf/2002/Ecore" name="DML"
    nsURI="http://modelum.es/DML" nsPrefix="DML">
  <eClassifiers xsi:type="ecore:EClass" name="InsertsStatements">
    <eStructuralFeatures xsi:type="ecore:EReference" name="insertsInto" upperBound="-1"
        eType="#//InsertInto" containment="true"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="InsertInto">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="tableName" lowerBound="1"
        eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString" defaultValueLiteral=""/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="registry" lowerBound="1"
        eType="#//Registry" containment="true"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="columns" upperBound="-1"
        eType="#//Column" containment="true"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="Registry">
    <eStructuralFeatures xsi:type="ecore:EReference" name="registryValues" upperBound="-1"
        eType="#//Value" containment="true"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="Column">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="columnName" lowerBound="1"
        eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="Value">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="value" lowerBound="1" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="column" lowerBound="1"
        eType="#//Column"/>
  </eClassifiers>
</ecore:EPackage>
