CREATE DATABASE IF NOT EXISTS TORNEOS;

CREATE TABLE ESTADIOS
(
	ESTADIO VARCHAR(30) NOT NULL,
	CAPACIDAD INT NOT NULL,
	CONSTRUCTORA VARCHAR(20) NOT NULL,
	SEDE_CONSTRUCTORA VARCHAR(20) NOT NULL,
	CONSTRAINT ESTADIOS_PK PRIMARY KEY(ESTADIO)	
);

CREATE TABLE PATROCINADORES
(
	PATROCINADOR VARCHAR(20) NOT NULL,
	SEDE VARCHAR(20) NOT NULL,
	CONSTRAINT PATROCINADOR_PK PRIMARY KEY(PATROCINADOR)
);

CREATE TABLE GANADORES_DE_TORNEOS
(
	TORNEO VARCHAR(20) NOT NULL,
	ANYO VARCHAR(4) NOT NULL,
	GANADOR VARCHAR(30) NOT NULL,
	FECHA_NAC_GANADOR DATE NOT NULL,
	ARBITRO VARCHAR(30) NOT NULL,
	FECHA_NAC_ARBITRO DATE NOT NULL,
	ESTADIO VARCHAR(30) NOT NULL,
	PATROCINADOR VARCHAR(20) NOT NULL,
	CONSTRAINT GANADORES_DE_TORNEOS_PK PRIMARY KEY(TORNEO, ANYO),
	CONSTRAINT ESTADIO_FK FOREIGN KEY(ESTADIO) REFERENCES ESTADIOS(ESTADIO)
);

ALTER TABLE GANADORES_DE_TORNEOS ADD CONSTRAINT PATROCINADOR_FK FOREIGN KEY(PATROCINADOR) REFERENCES PATROCINADORES(PATROCINADOR);